apiVersion: v1
kind: Service
metadata:
    name: etcd
    labels:
        app: etcd
spec:
    ports:
        - port: 2379
    selector:
        app: etcd
        tier: server
    type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pv-claim
  labels:
    app: etcd
spec:
    selector:
        matchLabels:
            type: local
            app: etcd
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
    name: etcd
    labels: 
      app: etcd
spec:
    replicas: 1
    selector:
        matchLabels:
            app: etcd
            tier: server
    template: 
        metadata:
            labels:
                app: etcd
                tier: server
        spec:
            containers:
                - name: etcd-server
                  image: quay.io/coreos/etcd:v2.3.7
                  args:
                    - -name
                    - etcd
                    - --data-dir
                    - /etcd_data
                    - -advertise-client-urls
                    - http://0.0.0.0:2379
                    - -listen-client-urls
                    - http://0.0.0.0:2379
                    - -initial-advertise-peer-urls
                    - http://0.0.0.0:2380
                    - -listen-peer-urls
                    - http://0.0.0.0:2380
                    - -initial-cluster
                    - etcd=http://0.0.0.0:2380
                  ports:
                    - containerPort: 2379
                      name: etcd
                      protocol: TCP
                  volumeMounts:
                    - name: etcd-persistent-storage
                      mountPath: /etcd_data
            volumes:
                - name: etcd-persistent-storage
                  persistentVolumeClaim:
                      claimName: etcd-pv-claim